language: java
jdk:
  - openjdk14

env:
  global:
    - CODECOV_TOKEN="9065edc4-ddf7-45ca-9a69-531c3e363900"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - anatoliy.gromov.service@gmail.com
    on_success: never # default: change
    on_failure: always # default: always